# Generated by Django 4.1.2 on 2023-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safeDesc', models.TextField()),
                ('doctorsAtWork', models.IntegerField(default=0)),
                ('SatisfiedPatient', models.IntegerField(default=0)),
                ('BedFacility', models.IntegerField(default=0)),
                ('Hospitals', models.IntegerField(default=0)),
            ],
        ),
    ]
