# Generated by Django 4.1.2 on 2023-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='HomeImage',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
