# Generated by Django 4.1.2 on 2023-06-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0002_homemodel_homeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckupsDesc', models.TextField()),
                ('TimeDesc', models.TextField()),
                ('ExpertDoctorsDesc', models.TextField()),
                ('MedicinesDesc', models.TextField()),
                ('BedFacilityDesc', models.TextField()),
                ('careDesc', models.TextField()),
            ],
        ),
    ]
