# Generated by Django 4.1.2 on 2023-06-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0003_servicesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUsImage', models.ImageField(upload_to='images')),
                ('aboutUsDesc', models.TextField()),
            ],
        ),
    ]
