# Generated by Django 4.1.2 on 2023-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0006_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewImage', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=200)),
                ('comments', models.TextField()),
            ],
        ),
    ]
