# Generated by Django 4.1.2 on 2023-06-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0007_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='reviewImage',
        ),
    ]
