# Generated by Django 4.1.2 on 2023-06-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0009_contactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='Message',
            new_name='message',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='image',
            field=models.ImageField(default='', null=None, upload_to='images'),
            preserve_default=False,
        ),
    ]
