# Generated by Django 4.1.2 on 2023-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0010_rename_message_contactmodel_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='ServiceName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
