# Generated by Django 4.1.2 on 2023-06-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0011_servicesmodel_servicename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='BedFacilityDesc',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='CheckupsDesc',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='ExpertDoctorsDesc',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='MedicinesDesc',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='TimeDesc',
        ),
    ]
