# Generated by Django 4.1.2 on 2023-06-26 05:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagement', '0012_remove_servicesmodel_bedfacilitydesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='Service_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='ServiceName', unique=True),
        ),
    ]
